# --- mega2560 ide 1.6
BOARD_TAG    = mega
BOARD_SUB    = atmega2560
MONITOR_PORT = /dev/tty.usbmodem1421
#ifndef MONITOR_PORT
#	$(error MONITOR_PORT not set. You can use `ls /dev/tty.*` to find a tty device.)
#endif
ARDUINO_DIR   = /Users/eric/Applications/Arduino.app/Contents/Java
include /usr/local/opt/arduino-mk/Arduino.mk

