# --- mega2560 ide 1.6
BOARD_TAG    = mega
BOARD_SUB    = atmega2560
MONITOR_PORT = /dev/tty.usbmodem1421
ARDUINO_DIR   = /Users/eric/Applications/Arduino.app/Contents/Java
USER_LIB_PATH := $(realpath ../libraries)
include /usr/local/opt/arduino-mk/Arduino.mk

